# -*- coding: utf-8 -*-
"""CapStone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EJ-H2INDmHa-Fupa0YXMPPqDLKE8Y8B
"""

!pip install paddlepaddle-gpu
!pip install paddleocr
!git clone https://github.com/PaddlePaddle/PaddleOCR

!git clone https://github.com/PaddlePaddle/PaddleOCR

!pip install gTTS gradio pdfminer.six

from paddleocr import PaddleOCR, draw_ocr
from matplotlib import pyplot as plt
from gtts import gTTS
from PIL import Image
import gradio as gr
import pickle
import cv2

ocr = PaddleOCR(lang='en',use_gpu=False)

import os
def extract(file):
  img_path=os.path.abspath(file)
  result = ocr.ocr(img_path)
  text=[]
  box=[]
  score=[]
  ##extractng text from img
  for block in result:
    for line in block:
      text.append(line[1][0])
      box.append(line[0])
      score.append(line[1][1])
  font_path='/content/PaddleOCR/doc/fonts/latin.ttf'
  img = cv2.imread(img_path)
  img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
  ##plotting the img
  plt.figure(figsize=(25,25))
  annoted=draw_ocr(img,box,text,score,font_path=font_path)
  plt.imshow(annoted)
  ##joining the text
  my_text=' '.join(text)
  #writing in file
  f = open('output.txt','w')
  f.write(my_text)
  f.close()
  ##text to mp3
  f= open('output.txt','r')
  read_file = f.read()
  myobj = gTTS(text=read_file,lang='en',slow=False)
  myobj.save('output.wav')
  return 'output.wav'

# res = extract('med1.png')

# print(res[1])


iface = gr.Interface(
    fn = extract,
    inputs='file',
    outputs='audio',
    title='Prescription Label Reading',
    description='Upload a image file and get the content as audio',
)
iface.launch()